version: "3.10"
services:

  web:
    build: .
    ports:
      - "8000:8000"
    networks:
      - main
    depends_on:
      - psql_db
      - cache
    volumes:
      - .:/code
    command: python manage.py runserver 0.0.0.0:8000
    container_name: api


  psql_db:
    image: postgres:13.13
    restart: no
    networks:
      - main
    volumes:
      - ./data/psql_db:/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres

    container_name: psql_db

  cache:
    image: redis:6.2-alpine
    networks:
      - main
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - ./cache:/data
    container_name: cache

volumes:
  web:

networks:
  main:
    name: main
